apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldb-pv
  namespace: default
  labels:
    storage: mysqldb-pv
    name: mysqldb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/data1"