---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
  - port: 3306
    targetPort: 3306
--- 
apiVersion: v1
kind: Service
metadata:
  name: todoapi
spec:
  selector:
    app: todoapi
  ports:
  - port: 4100
    targetPort: 4100
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - nodePort: 30206  
    port: 4200
    targetPort: 4200   
  type: NodePort     
