apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  serviceName: mysqldb-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: docker.io/mysql:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"        
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mytodoapp
        - name: MYSQL_DATABASE
          value: todoapp
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mysqldb-pvc 
