apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-configmap
data:
  todo-api.properties: |
    APP_PORT=4100
    MYSQL_HOST=mysqldb
    MYSQL_PORT=3306
    MYSQL_USER=root
    MYSQL_PASS=mytodoapp
    MYSQL_DB=todoapp
  web-app-config.properties: |
    [todo-api]
    Scheme=http
    Host=todoapi
    Port=4100
    [frontend]
    ParallelThreads=2